### ISSUE TITLE
期待技术交流

### ISSUE THREAD

**Issue by qiuchengw** [seerline/clchart#15]
我也开源了一个交易图表（SiaChart），
地址：https://github.com/qiuchengw/siachart
文档：https://qiuchengw.github.io/zh-cn/

本来写了一封邮件给各位以期交流，但是邮件被系统退信，所以在这儿提一个issue，希望能和各位交流交易方面的开发技术。握手🤝

**Comment by coollyer** [comment]
看了你的项目，感觉我们走的路完全不同啊！有兴趣交流加微信：13816575798

**Comment by WaiSiuKei** [comment]
我写的仿 TradingView Chart, 思路也是双层<canvas>
https://github.com/WaiSiuKei/nila3

**Comment by qiuchengw** [comment]
> 我写的仿 TradingView Chart, 思路也是双层
> https://github.com/WaiSiuKei/nila3

没有开源？
