### ISSUE TITLE
手势操作与深度图

### ISSUE THREAD

**Issue by usercao** [seerline/clchart#16]
希望加入K线图柱状图左右拖动的手势操作和交易深度图
![image](https://user-images.githubusercontent.com/13760476/53462904-5b177680-3a80-11e9-96d8-229c299c0f67.png)

**Comment by coollyer** [comment]
这应该算是个插件吧，你可以在这个系统上自己构建的啊，我有计划构建一个基于插件的图表系统，有机会交流；
