### ISSUE TITLE
使用Python 的web加载index报ClChart is not defined错

### ISSUE THREAD

**Issue by lignpeng** [seerline/clchart#7]
1、使用Python 的web加载index报ClChart is not defined错
1）web对象：
self.webView = QWebEngineView(self.centralwidget)
2）使用：
file_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "index/index.html")) 
local_url = QUrl.fromLocalFile(file_path)
self.ui.webView.load(local_url)
web一直loading旋转，日志提示：
js: Uncaught ReferenceError: ClChart is not defined

3）尝试把ClChart.js代码放到HTML，还是报错。

2、但是使用浏览器可以正常打开。

**Comment by lignpeng** [comment]
1、尝试去编译，但是编译失败，这是日志：
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'docs:build' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'predocs:build', 'docs:build', 'postdocs:build' ]
5 info lifecycle clchart@0.1.0~predocs:build: clchart@0.1.0
6 info lifecycle clchart@0.1.0~docs:build: clchart@0.1.0
7 verbose lifecycle clchart@0.1.0~docs:build: unsafe-perm in lifecycle true
8 verbose lifecycle clchart@0.1.0~docs:build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/lignpeng/clchart/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/anaconda2/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin
9 verbose lifecycle clchart@0.1.0~docs:build: CWD: /Users/lignpeng/clchart
10 silly lifecycle clchart@0.1.0~docs:build: Args: [ '-c', 'vuepress build docs' ]
11 info lifecycle clchart@0.1.0~docs:build: Failed to exec docs:build script
12 verbose stack Error: clchart@0.1.0 docs:build: `vuepress build docs`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:915:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid clchart@0.1.0
14 verbose cwd /Users/lignpeng/clchart
15 verbose Darwin 17.3.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "docs:build"
17 verbose node v8.12.0
18 verbose npm  v6.4.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error clchart@0.1.0 docs:build: `vuepress build docs`
23 error spawn ENOENT
24 error Failed at the clchart@0.1.0 docs:build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

对这方面的知识不是很熟悉，😂。
2、下载了0.0.6版本低clchart.js，就出现一开始的问题。

能上传一个最新的编译好的js文件么，谢谢哈

**Comment by Micjoyce** [comment]
你尝试下载 [0.1.0](https://github.com/seerline/clchart/releases/tag/v0.1.0)试一下

**Comment by lignpeng** [comment]
尝试几次了0.1.0，编译还是不行
> clchart@0.1.0 docs:build /Users/lignpeng
> vuepress build docs
sh: vuepress: command not found
也是提示，同样的编译错误。
不知道需要安装什么工具，目前就是安装了nodejs，Mac本。

0.1.0版本没有找到编译好的clchart.js文件

**Comment by lignpeng** [comment]
编译一直不通过，编译bug一直不断出现

**Comment by Micjoyce** [comment]
@lignpeng 这个仓库放的是我编译好的，你下载下来看下[https://github.com/seerline/clchart.samples](https://github.com/seerline/clchart.samples)再试试

**Comment by lignpeng** [comment]
@Micjoyce 下载clchart.samples，替换掉原来的文件，重新加载，可以展示出来了
谢谢！
