### ISSUE TITLE
这个demo的源码能分享下吗，非常感谢！

### ISSUE THREAD

**Issue by wuyeguangming** [seerline/clchart#9]
如图：https://github.com/seerline/clchart.react-native.demo/blob/master/source/seer.png

**Comment by Micjoyce** [comment]
@wuyeguangming  [https://github.com/seerline/clchart.react-native.demo](https://github.com/seerline/clchart.react-native.demo)源码在这

**Comment by wuyeguangming** [comment]
> @wuyeguangming https://github.com/seerline/clchart.react-native.demo源码在这这个项目里面。具体的实现是在 clchart plugin中https://github.com/seerline/clchart/tree/master/src/plugins
真是太棒了！
